"""Conformance: every SDK must produce identical bytes for each vector.

Reads `docs/test-vectors/vectors.json` (generated by `generate_vectors.py`)
and asserts that the Python implementation reproduces the recorded
`expected_hex` exactly. The TS and Rust SDKs run the same conformance
suite against the same JSON.

If you intentionally change byte format, regenerate vectors with
`uv run python -m tests.generate_vectors` and bump the SPEC version.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from arthash import Codec, ShapeType, encode

REPO_ROOT = Path(__file__).resolve().parents[3]
VECTORS_PATH = REPO_ROOT / "docs" / "test-vectors" / "vectors.json"


def _load_vectors():
    if not VECTORS_PATH.exists():
        pytest.skip(f"test vectors not generated yet: {VECTORS_PATH}")
    return json.loads(VECTORS_PATH.read_text(encoding="utf-8"))["vectors"]


def _hex_to_palette(palette_hex: list[str]) -> np.ndarray:
    out = np.zeros((len(palette_hex), 3), dtype=np.uint8)
    for i, h in enumerate(palette_hex):
        out[i] = [int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)]
    return out


def _build_input(input_spec: dict) -> np.ndarray:
    """Mirror the generators in `generate_vectors.py`."""
    kind = input_spec["kind"]
    h, w = input_spec["h"], input_spec["w"]
    if kind == "solid":
        rgb = input_spec["rgb"]
        arr = np.zeros((h, w, 3), dtype=np.uint8)
        arr[..., 0] = rgb[0]
        arr[..., 1] = rgb[1]
        arr[..., 2] = rgb[2]
        return arr
    if kind == "gradient":
        arr = np.zeros((h, w, 3), dtype=np.uint8)
        arr[..., 0] = np.linspace(0, 255, w, dtype=np.uint8)[None, :]
        arr[..., 1] = np.linspace(0, 255, h, dtype=np.uint8)[:, None]
        arr[..., 2] = 64
        return arr
    if kind == "random":
        rng = np.random.default_rng(input_spec["seed"])
        return (rng.random((h, w, 3)) * 255).astype(np.uint8)
    raise ValueError(f"unknown input kind: {kind!r}")


def _build_codec(codec_spec: dict) -> Codec:
    kwargs: dict = {
        "shape": ShapeType(codec_spec["shape"]),
        "n_shapes": codec_spec["n_shapes"],
        "cx_bits": codec_spec["cx_bits"],
        "cy_bits": codec_spec["cy_bits"],
        "r_bits": codec_spec["r_bits"],
        "alpha_bits": codec_spec["alpha_bits"],
        "color_bits": codec_spec["color_bits"],
    }
    if "palette_hex" in codec_spec:
        kwargs["palette"] = _hex_to_palette(codec_spec["palette_hex"])
        if "palette_k" in codec_spec:
            kwargs["palette_k"] = codec_spec["palette_k"]
    if "alpha_levels" in codec_spec:
        kwargs["alpha_levels"] = np.array(codec_spec["alpha_levels"], dtype=np.float32)
    if "grid_aspect" in codec_spec:
        kwargs["grid_aspect"] = codec_spec["grid_aspect"]
    return Codec(**kwargs)


@pytest.mark.parametrize("vec", _load_vectors(), ids=lambda v: v["name"])
def test_vector_reproduces_expected_hex(vec):
    img = _build_input(vec["input"])
    codec = _build_codec(vec["codec"])
    actual = encode(img, codec, **vec.get("encode_kwargs", {}))
    expected = bytes.fromhex(vec["expected_hex"])
    assert actual == expected, (
        f"vector {vec['name']}: mismatch\n"
        f"  expected: {expected.hex()}\n"
        f"  actual:   {actual.hex()}"
    )
    assert len(actual) == vec["expected_bytes"]
